import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import { UserProvider } from '../components/UserProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RAGify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className="bg-white dark:bg-gray-900 text-black dark:text-white">
        <header className="p-4 border-b border-gray-200 dark:border-gray-700">
          <h1 className="text-lg font-bold">RAGify</h1>
        </header>
        <UserProvider>
          <main>{children}</main>
        </UserProvider> 
      </body>
      </html>
  );
}
